# ---
# public_date: 2025-10-14
# update_dade: 2025-10-14
# version: 1.0.0
# ---
name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      mode:
        description: "attach = 既存artifactsを添付 / build = CIでビルドして添付"
        required: true
        default: "attach"
        type: choice
        options: [attach, build]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      MODE: ${{ steps.set.outputs.MODE }}
      TAG: ${{ steps.tag.outputs.TAG }}
    steps:
      - name: Resolve mode
        id: set
        run: echo "MODE=${{ github.event.inputs.mode || 'attach' }}" >> "$GITHUB_OUTPUT"
      - name: Resolve tag
        id: tag
        run: |
          ref="${GITHUB_REF##*/}"
          echo "TAG=${ref}" >> "$GITHUB_OUTPUT"

  build:
    if: ${{ needs.prepare.outputs.MODE == 'build' }}
    needs: prepare
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Enable corepack & install
        run: |
          corepack enable
          pnpm i --frozen-lockfile || npm ci
      - name: Build artifacts
        run: |
          node scripts/build.mjs || npm run build
          node scripts/package.mjs || echo "skip package"
      - name: Generate checksums
        shell: bash
        run: |
          mkdir -p artifacts
          find artifacts -type f -maxdepth 1 -print0 2>/dev/null || true
          [ -d artifacts ] && (cd artifacts && for f in *; do [ -f "$f" ] && shasum -a 256 "$f" >> SHA256SUMS.txt || true; done)
      - name: Upload CI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: artifacts/**

  collect:
    if: ${{ needs.prepare.outputs.MODE == 'build' }}
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: collected
      - name: Pack collected
        run: |
          mkdir -p release
          cp -R collected/*/* release/ || true
      - name: Upload packed
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: release/**

  attach:
    if: ${{ needs.prepare.outputs.MODE == 'attach' }}
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare artifacts (repo内artifacts配下に置いた場合)
        run: |
          mkdir -p artifacts
          [ -d artifacts ] || exit 0
          if [ -d artifacts ]; then
            (cd artifacts && for f in *; do [ -f "$f" ] && shasum -a 256 "$f" >> SHA256SUMS.txt || true; done)
          fi
      - name: Upload local artifacts
        if: ${{ hashFiles('artifacts/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: artifacts/**

  publish:
    needs: [prepare, collect, attach]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-bundle
          path: out
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare.outputs.TAG }}
          draft: false
          prerelease: false
          files: |
            out/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}